{% set version = '3.0-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-raster
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/raster_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/raster/raster_{{ version }}.tar.gz
  sha256: 3fbef60ad621b42e04536349362c9ecdceaaace823fe2d3ff1d4c7f0d480987c

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-sp >=1.2_0
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp
    - r-sp >=1.2_0

test:
  commands:
    - $R -e "library('raster')"           # [not win]
    - "\"%R%\" -e \"library('raster')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=raster
  license: GPL-3
  summary: Reading, writing, manipulating, analyzing and modeling of gridded spatial data. The
    package implements basic and high-level functions. Processing of very large files
    is supported. There is a also support for vector data operations such as intersections.
    See the manual and tutorials on <https://rspatial.org/> to get started.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: raster
# Type: Package
# Title: Geographic Data Analysis and Modeling
# Version: 3.0-2
# Date: 2019-08-22
# Depends: sp (>= 1.2-0), R (>= 3.0.0)
# Suggests: rgdal (>= 0.9-1), rgeos (>= 0.3-8), ncdf4, igraph, tcltk, parallel, rasterVis, MASS, sf, testthat
# LinkingTo: Rcpp
# Imports: Rcpp, methods
# SystemRequirements: C++11
# Description: Reading, writing, manipulating, analyzing and modeling of gridded spatial data. The package implements basic and high-level functions. Processing of very large files is supported. There is a also support for vector data operations such as intersections. See the manual and tutorials on <https://rspatial.org/> to get started.
# License: GPL (>= 3)
# URL: https://CRAN.R-project.org/package=raster
# BugReports: https://github.com/rspatial/raster/issues/
# Authors@R: c( person("Robert J.", "Hijmans", role = c("cre", "aut"),   email = "r.hijmans@gmail.com",  comment = c(ORCID = "0000-0001-5872-2872")), person("Jacob", "van Etten", role = "ctb"), person("Michael", "Sumner", role = "ctb"), person("Joe", "Cheng", role = "ctb"), person("Andrew", "Bevan", role = "ctb"), person("Roger", "Bivand", role = "ctb"), person("Lorenzo", "Busetto", role = "ctb"), person("Mort", "Canty", role = "ctb"), person("David", "Forrest", role = "ctb"), person("Aniruddha", "Ghosh", role = "ctb"), person("Duncan", "Golicher", role = "ctb"), person("Josh", "Gray", role = "ctb"), person("Jonathan A.", "Greenberg", role = "ctb"), person("Paul", "Hiemstra", role = "ctb"), person("Institute for Mathematics Applied Geosciences", role="cph"), person("Charles", "Karney", role = "ctb"), person("Matteo", "Mattiuzzi", role = "ctb"), person("Steven", "Mosher", role = "ctb"), person("Jakub", "Nowosad", role = "ctb"), person("Edzer", "Pebesma", role = "ctb"), person("Oscar", "Perpinan Lamigueiro", role = "ctb"), person("Etienne B.", "Racine", role = "ctb"), person("Barry", "Rowlingson", role = "ctb"), person("Ashton", "Shortridge", role = "ctb"), person("Bill", "Venables", role = "ctb"), person("Rafael", "Wueest", role = "ctb") )
# NeedsCompilation: yes
# Packaged: 2019-08-22 17:02:34 UTC; rhijm
# Author: Robert J. Hijmans [cre, aut] (<https://orcid.org/0000-0001-5872-2872>), Jacob van Etten [ctb], Michael Sumner [ctb], Joe Cheng [ctb], Andrew Bevan [ctb], Roger Bivand [ctb], Lorenzo Busetto [ctb], Mort Canty [ctb], David Forrest [ctb], Aniruddha Ghosh [ctb], Duncan Golicher [ctb], Josh Gray [ctb], Jonathan A. Greenberg [ctb], Paul Hiemstra [ctb], Institute for Mathematics Applied Geosciences [cph], Charles Karney [ctb], Matteo Mattiuzzi [ctb], Steven Mosher [ctb], Jakub Nowosad [ctb], Edzer Pebesma [ctb], Oscar Perpinan Lamigueiro [ctb], Etienne B. Racine [ctb], Barry Rowlingson [ctb], Ashton Shortridge [ctb], Bill Venables [ctb], Rafael Wueest [ctb]
# Maintainer: Robert J. Hijmans <r.hijmans@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-08-22 21:50:02 UTC
