{% set version = "3.6-30" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-raster
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/raster_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/raster/raster_{{ version }}.tar.gz
  sha256: bb7f634a52d6b02639bc9fa5719862a814b51d5b2798472d6dd28612844a3070

build:
  skip: true  # [ppc64le or win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-sp                         # [build_platform != target_platform]
    - r-terra                      # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-codetools
    - r-rcpp
    - r-sp >=1.4.5
    - r-terra >=1.6-41
  run:
    - r-base
    - r-rcpp
    - r-sp >=1.4.5
    - r-terra >=1.6-41

test:
  requires:
    - r-codetools
    - r-tinytest
  commands:
    - $R -e "library('raster')"                          # [not win]
    - $R -e "tinytest::test_package('raster')"           # [not win]
    - "\"%R%\" -e \"library('raster')\""                 # [win]
    - "\"%R%\" -e \"tinytest::test_package('raster')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=raster
  dev_url: https://github.com/rspatial/raster
  license: GPL-3.0-or-later
  summary: Reading, writing, manipulating, analyzing and modeling of gridded spatial data. The package implements basic and high-level functions. Processing of very large files is supported. There is a also support for vector data operations such as intersections. See the manual and tutorials on <https://rspatial.org/> to
    get started.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
