{% set version = '2.6-7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-raster
  version: {{ version|replace("-", "_") }}

source:
  fn: raster_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/raster_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/raster/raster_{{ version }}.tar.gz
  sha256: fb91804fd465a4a6d9d9858e29fd05f41a99b8efdcc5cf4370ea253b68e42b01

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rcpp
    - r-sp >=1.2_0

  run:
    - r-base
    - r-rcpp
    - r-sp >=1.2_0

test:
  commands:
    - $R -e "library('raster')"  # [not win]
    - "\"%R%\" -e \"library('raster')\""  # [win]

about:
  home: http://cran.r-project.org/package=raster
  license: GPL (>= 3)
  summary: Reading, writing, manipulating, analyzing and modeling of gridded spatial data. The
    package implements basic and high-level functions. Processing of very large files
    is supported.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
