appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: rBHmJiSjMyorTk6v+hKWLPELN53MPFZzICv1byOPZ85EGJIQ8oGbK6dY27enY/tWlsPajSqC1lSQPZlhqghFLgaWb3oKpRyj/pUOaPiBbqjssMddgjwOlEw5NrQbXZaDDtXDNL1m2Kj2zVwiq/hM91vkZhuiMV//hmNBnzsacwNBz6oVck6LQspJ2KjUdWxltXrpCaiP0mc5ogIRyXgIq4hmnz4S/oCZiIeohZFu+iIVe7JIRhLsTgl+G0NoogHEGULkC2Ry8g164xsCHQzmrqEWlcQHxseMZkIk+ha6ceya2Ma1j/fgKQyOs7q6fT5MywFtGCmUXjDojf7134AZbTrRgB5zrCnjxxgAVb9TOJkl1WjoZzLVIPspGZeijKOC9uF/K3GEazsbCEzcfYkAMwGux+FFqWo4usfdY+mstih9fklRJMbSskR8uGlSNgj+QG1eOOWsYPQkAOUWvDYo7kVGpa7oWWRmSn600ItnOOTaaA4WXb0RclaDAvj3GjC8o9vevptPODoz3i5UQVbi76fNFNMGwogOXcQfADILvTa7TLLzIZKeBsSYwW8xup9XiChgmrFNvIAPyxxEk5SbdTAiajcsvOIsN8qmO9QrITLrtYISkqODOUhSq3cw8wjk/GXL60lab20IGAYh4JjBybm3o1T0jXcpWSnEmrVFY2g=}
bot:
  automerge: true
